### ISSUE TITLE
[1.10] Thermal Expansion - Compactor

### ISSUE THREAD

**Issue by Magi1053** [MinecraftModDevelopmentMods/BaseMetals#171]
Thermal Expansions's Compactor - Press takes ingots and makes plates. Looking at recipies in JEI I see that I can put basemetal ingots into the compactor, but when actually try to do it, the machine does not accept the ingots in it's input.

**Comment by dshadowwolf** [comment]
The integration there is... touchy and I've not been able to really dig into it because some other issues that keep coming up and interfering with making it work. We have been trying - there is an issue where, sometimes, a null-itemstack will make it into a recipe and cause a major conflict/crash when BaseMetals and TE are used together.

At this time neither myself nor @jriwanek have been able to figure out what is causing that, sadly.

**Comment by dshadowwolf** [comment]
Testing a fix for this now - the TE interface code was basically untouched since it was 90% disabled when the original errors started coming in back in 1.10 and followed into 1.11 ... I'm hoping the registry changes in 1.12 fix this.

**Comment by dshadowwolf** [comment]
should be working on -beta3.49
