### ISSUE TITLE
Buckets

### ISSUE THREAD

**Issue by D3nnis3n** [MinecraftModDevelopmentMods/BaseMetals#178]
A Little Suggestion: What about adding buckets for the different materials?

**Comment by dshadowwolf** [comment]
Have a mod that is deep pre-alpha and needs porting from 1.10 for this. It also needs somewhat rewritten and somebody that knows the fluid caps system to help.

See: https://github.com/MinecraftModDevelopmentMods/MMDBuckets

I haven't touched it since March - and that was handing it over to MMD from the initial private devel. Any help would be appreciated.

**Comment by D3nnis3n** [comment]
Why an extra mod for this? At the Moment i just use some recipes for other metals that produce normal buckets, especially because most bucket mods out there do not work with mod fluids.

**Comment by dshadowwolf** [comment]
Mostly because the code for fluid handling and interaction isn't something anyone on the MMD Team is really comfortable with and then, also, because it was written so all the buckets are metadata variations.
