### ISSUE TITLE
B:EnableEmerald=false still generates (unlocalized) molten emerald

### ISSUE THREAD

**Issue by Thyriel** [MinecraftModDevelopmentMods/BaseMetals#212]
As title. B:EnableEmerald=false in config still generates molten emerald for  Tinker Construct and overwrites the TC's own molten emerald with fluid. basemetals.emerald.name (no idea why you even try to add that as TC has it's own molten emerald for the pigiron alloy)

Same setting for Diamonds works correctly and disables molten diamond as well.

Base Metals 2.5.0-beta2.31

**Comment by dshadowwolf** [comment]
After this release was made it was found that the, at the time believed to be, minor issues in the Tinkers' Construct interface are actually indicative of deeper problems caused by a less than complete understanding, on our part, of the timing and phases of Tinkers' loading in 1.12

With that in mind... Some of what occurs with Emerald in the plugin is due to there being some experimental code for casting some Base Metals pieces with Tinkers that is going to be removed.

**Comment by dshadowwolf** [comment]
New versions of all the *metals mods released on Curse. Does this issue still persist ?

**Comment by dshadowwolf** [comment]
With fluids now a configuration option, this issue should be resolved.
