### ISSUE TITLE
Silver Crack Hammer causing crash when used to attack Mo'Creatures Werewolf

### ISSUE THREAD

**Issue by Twilix01** [MinecraftModDevelopmentMods/BaseMetals#329]
Crash log here: https://pastebin.com/ZqQgrCuu

I tested to make sure it was only the Silver Hammer and that is indeed the cause, no other weapon I have installed has reproduced this.

My guess would be that the way Mo'Creatures handles silver weapons doing extra damage to werewolves is that it expects it to be classified as a "sword", but I don't know the code well of either of these mods so I could be wrong.

Is this something that can be fixed on this end? Or is it solely the fault of Mo'Creatures?

**Comment by dshadowwolf** [comment]
No way we can fix it on our end.

Crackhammers are not weapons and are not mining tools - they are processing tools. Yes, they can mine and, yes, they can do damage, but that is because of how Minecraft itself handles items.

It looks like they expect all tools to be able to be cast to "ItemSword" - which seems (to me) to be, frankly, idiotic. Shovels, Pickaxes and all the other tools are all "extends ItemTool" and swords - vanilla swords are "extends Item". Yes, "ItemTool" does "extend Item" but sharing an ancestor like that does not make a cast possible.

I have a feeling that you might see a similar result (unless they have specifically guarded against it) with Tinkers' Construct tools made of Silver... In any case...

No - this is not something we could fix on our end. Mo' Creatures seems to be doing something very, very wrong.

**Comment by Twilix01** [comment]
Strangely I don't have the crash with tinker's construct tools/weapons, it just does not do extra damage. Thank you for the quick response! I will take this issue up with the developer(s) of Mo'Creatures now, would it be alright to tell them what you've said?

**Comment by dshadowwolf** [comment]
I don't have a copy of the Mo' Creatures code (it's not open/visible source) to back up my statements - so I'm not that positive about them, but the error does seem to point in that direction. So... feel free, but I might be missing something entirely that they are doing since I can't actually look to see (not without doing something that would violate their copyright)

**Comment by Twilix01** [comment]
Very well! Thank you again, I will be closing this issue now as I now know it's not on you to fix, have a good one!
