### ISSUE TITLE
Many smelting recipe errors with BaseMetals-1.12-2.5.0-beta5.214

### ISSUE THREAD

**Issue by Wabbit0101** [MinecraftModDevelopmentMods/BaseMetals#341]
No sure if recipes are being registered twice (first set of logs). The "minecraft:air" ones do seem broken though. Full set of messages here: [https://pastebin.com/SsjPjBJa](https://pastebin.com/SsjPjBJa). 

**Environment details:**
Java is version 1.8.0_171, 64bit
Forge-1.12.2-14.23.3.2655
OreSpawn-1.12-3.3.0.136
BaseMetals-1.12-2.5.0-beta5.214

**Comment by dshadowwolf** [comment]
Actually... it's because of the "Furnace Cheese" in vanilla that gives you a single nugget back that those errors are showing up. This is already fixed in dev and, as soon as we've got the 1.11 and 1.10 versions as close to an exact code match as possible with the 1.12 code there will be a fresh release on CurseForge containing that fix among many others.

**Comment by jriwanek** [comment]
Should be fixed in beta6.
