### ISSUE TITLE
Certain cfg options can lead to tinker's construct integration breaking

### ISSUE THREAD

**Issue by terrapin47** [MinecraftModDevelopmentMods/BaseMetals#359]
Minecraft: 1.12.2
Base Metals: 1.12-2.5.0-beta5.214
Tconstruct: 1.12.2-2.10.1.87

I'm not sure exactly what is causing this issue, but I'll give all the information I can.

Having a certain specific configuration file setup will lead to tinker's construct integration breaking, which is shown below. ( No tinker's tools from base metals materials will show in JEI or are able to be produced, and base metals materials will not melt in the tconstruct smeltery ).

https://pastebin.com/GxxMqwUV

From this point, if you disable under metals: invar and brass items and materials, then the issue seems to correct itself.

From my debug logs on launching the game, there is a clue.

https://pastebin.com/eTJ03qx5

Steps to reproduce:

Install the latest versions of base metals and tconstruct as listed above.
Use the configuration file linked above.
Note that tinker's integration is broken.

**Comment by dshadowwolf** [comment]
Could you see if you can replicate this with the latest version available on our [Maven](https://maven.mcmoddev.com/com/mcmoddev/BaseMetals/)? There was recently a lot of work to fix numerous bugs in the integration. (should be -beta5.275 or so)

If this bug still occurs with the latest version, then there is some work needed to track down the cause of this one. 

Thanks for the report and I'm hoping that this turns out to have already been resolved :)

**Comment by terrapin47** [comment]
The issue does appear to be fixed there, yes.

**Comment by dshadowwolf** [comment]
Thank you for that - I spent more than three days working on fixing all the issues that existed in the Tinkers' interaction code. A lot of them because the original version of it had been written before I had gained a lot of skill with Java and also before I knew what all was going to be needed. It was complex, hard to maintain and broke with each MC version change and almost every Tinkers' version change.

While this new code is a lot simpler and hopefully more robust, I was not looking forward to having to fix it again so soon.
