### ISSUE TITLE
Fatally Missing Registry Entries only on my PC

### ISSUE THREAD

**Issue by CowHItFace** [MinecraftModDevelopmentMods/BaseMetals#454]
For some reason this message only pops up on my PC but my mate can enter the server without any hustle. It also has something to do with this mod because when i uninstall the mod from my server and the client, everything is working correctly for some reason.

Latest client log
[latest.log](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/3543281/latest.log)

**Comment by dshadowwolf** [comment]
This looks like the server and your client are running different versions of MMDLib. MMDLib -rc1 and the version of BaseMetals that goes with it had a bad change brought on by a bad decision on my part - the messages at the tail end of your log suggest that either you are running MMDLib -rc1 or the server is. Mod versions ***MUST*** match because of issues like that.  (Late Edit: Note that the current MMDLib is -rc2 and that is the one you should be using)

**Comment by CowHItFace** [comment]
It works thx :D
