### ISSUE TITLE
About #482

### ISSUE THREAD

**Issue by Kasia1403** [MinecraftModDevelopmentMods/BaseMetals#483]
Here is a screenshot of mushrooms in air :

![2022-03-02_11 43 46](https://user-images.githubusercontent.com/54236098/156347837-34ffafb5-2f3a-472d-9df4-59adfc1fff8f.png)

About This issue where I can't move : It's very similar to server lag or very similar to that when player spawns in a block and suffocates and death message is like that : ( player name ) suffocated in a wall. I don't know how to record a video in Minecraft.

**Comment by dshadowwolf** [comment]
...Unless you're using the "Fallback Generator" (which is completely brain-dead and only exists because people don't seem to get "This needs MMD OreSpawn or a similar mod") this mod does no world-gen on its own and only provides materials and blocks that other mods can add-in and/or spawn. You've given insufficient information to even begin to try and replicate this issue and seem to just be pointing at a mod without actually saying why you think it is this mod, specifically, that is at fault.

That is not to say you are not having a real issue, but there is no AI, no "special rendering", no world-generation, no "tile entities"... The only "special" effect that might happen is if you're using a suit of armor that provides a benefit for wearing a full suit - and you've not even mentioned this.

I really would like to help, but without information about why you believe it is BaseMetals causing this - and without information enough that I can actually replicate the issue myself - there is nothing I can actually do. Programming is not magic - it is logic and I have no clue _HOW_ the code I've worked on and/or written could be causing anything like this, so more information is actually needed.

(Note: if you can not - or will not - provide more information this issue will just be closed)

**Comment by Kasia1403** [comment]
I still don't understand what is "Fallback Generator". I belive that my issues are caused by Base Metals and/or Base Minerals because when I disabled them the bugs were not occuring ( hope my english is OK, I'm from Poland ). But I don't want to play without theese mods. I think that Base Metals and/or Base Minerals have a conflict or are incompatible with at least one of other mods from my modpack, but I don't know with which.

**Comment by dshadowwolf** [comment]
Okay...
1) BaseMetals and friends do not have any code that runs _actively_ in the game unless you are wearing, eg: a full suit of Adamantine Armor - the only code that comes close to being "active" like that is the "Fallback Generator for Ore Spawns"
(Okay, okay, so there is a tiny bit of "active" code in NetherMetals for the whole "things mined can explode" bit, but...)

2) As previously stated... Without enough information that _I_ could use to replicate this bug, I cannot do anything as I have no clue what could be causing issues like this. Our code works as close to how Minecraft itself works for all the items and blocks as possible when working from a translation of a translation of a piece of code, so it should actually be relatively performant (to the same extent the vanilla code-base is) and incapable of introducing latency/lag on the level you're speaking of.

3) I really would love to help, but I am not a magician able to see your computer from my seat in another country and tell what is going on. Instead I am just a programmer with a sometimes fun hobby, so any log-files, mod-lists and such that you could provide from a run of the game where the issue occurs would be extremely helpful in finding out what is going on.

**Comment by Kasia1403** [comment]
[debug.log](https://github.com/MinecraftModDevelopmentMods/BaseMetals/files/8169584/debug.log)
Is it the debug information ? This is my debug.log file. I don't understand what means debug ( or to debug ).

**Comment by Kasia1403** [comment]
About my computer:

Processor AMD-FX 6300 3,5 GHz
16GB RAM
Windows 10 x64
Graphic card is NVIDIA GeForce GTX 750 TI

**Comment by dshadowwolf** [comment]
Thank you - that does help. I'm going to go talk with the rest of the team, as I see a couple mods mentioned that I'm not sure we have ever tested full compatibility with.

Beyond that... I really do need to talk with the team, as I have some concerns about possible cross-mod interactions and more with some other things I'm seeing in the log, thank you.

**Comment by Kasia1403** [comment]
Could I know what are You seeing in the log ? Is it something that I will understand ? Maybe I will learn something about how to check mod compatibilities or incompatibilities ?

**Comment by dshadowwolf** [comment]
Its more... We tried to do things as close to how the Vanilla code does them as possible to cut down on the number of issues with other mods, but... There are some mods we have never, actually, tested against because of either time constraints or because we just didn't think of them. Geolosys and Metallurgy are two of them - we've had a couple reports of issues with Geolosys, but never anything that could be replicated - and have never had any issues (that I know of) reported with Metallurgy, but part of the practice of writing code and debugging is to try and remove as much as possible from the possible sources of error in order to find out what is actually causing the problem(s). So most of what I'm going to be talking with them about is possible sources of the issue to see if we can... "simplify" the space to try and figure out what is going on.

**Comment by dshadowwolf** [comment]
Okay - without getting a response from the team I can state that I have two concerns about the mods you're using.

1) Unidict - this mod does some things, especially with BaseMetals and BaseMinerals, in sometimes very poorly chosen manners and has been known to cause issues in the past. I believe we have them solved, but my memory has gotten rather crappy since I turned 40 a few years ago and cannot say for sure.

2) Anything made using `MCreator`.  While a simplified modding system - which is what MCreator is - is not a bad idea, MCreator historically has had so many issues that it was against the CurseForge terms of service to distribute MCreator mods on their site for a very long time. I can see that you have between 6 and 12 different mods in your pack that are MCreator mods and while I don't know the quality of the system since it has gone fully open source, the history there has me concerned that they might be causing some issues that are just triggered when BaseMetals or MMD OreSpawn run.

3) This issue might be because it looks like 60+ mods are doing world-generation of some sort (there are sections of around 130 lines in the log-file you posted that "Profile" World Generation - with it being 2 lines per mod/call, that makes 65 mods).  I do not know for certain, however, and this is why I'm going to be spending a lot of time talking to the rest of the team to see if we can narrow things down or figure out exactly where the issue is coming from.

**Comment by Kasia1403** [comment]
Installed Base Metals, Base Minerals, MMD Orespawn, Metallurgy 4 Reforged, Geolosys, MMDLib and Modern Metals and theese bugs didn't appear.

**Comment by dshadowwolf** [comment]
> Installed Base Metals, Base Minerals, MMD Orespawn, Metallurgy 4 Reforged, Geolosys, MMDLib and Modern Metals and theese bugs didn't appear.

This clears up some worries and helps us a lot, thank you for putting in that extra work!

**Comment by Kasia1403** [comment]
Oh, so You are saying that maybe the mods created with MCreator may cause problems ? I read that this program is to create mods without any knowledge of Java language, so I think this program is not very good and maybe theese mods created with it really can cause issues. Maybe MCreator should be illegal to use ?

**Comment by Kasia1403** [comment]
Installed Silent's Gems and it is still OK.

**Comment by dshadowwolf** [comment]
> Oh, so You are saying that maybe the mods created with MCreator may cause problems ? I read that this program is to create mods without any knowledge of Java language, so I think this program is not very good and maybe theese mods created with it really can cause issues. Maybe MCreator should be illegal to use ?

Please note that my experience with MCreator and the mods it creates is more than 2 years old and I was speaking of things as they were years ago. I have concerns about mods made using the MCreator system because it has, to my knowledge, not been a good system and the source of major issues. I do _NOT_ know if the issues with compatibility have been addressed, nor do I know if any of the other issues have been resolved.

It is only because of the history of MCreator made mods being... very poorly made that I have concerns about those mods.

**Comment by Kasia1403** [comment]
Did You found something new ?

**Comment by dshadowwolf** [comment]
My day-job is getting in the way, sorry.

**Comment by Kasia1403** [comment]
> Okay - without getting a response from the team I can state that I have two concerns about the mods you're using.
> 
>     1. Unidict - this mod does some things, especially with BaseMetals and BaseMinerals, in sometimes very poorly chosen manners and has been known to cause issues in the past. I believe we have them solved, but my memory has gotten rather crappy since I turned 40 a few years ago and cannot say for sure.
> 
>     2. Anything made using `MCreator`.  While a simplified modding system - which is what MCreator is - is not a bad idea, MCreator historically has had so many issues that it was against the CurseForge terms of service to distribute MCreator mods on their site for a very long time. I can see that you have between 6 and 12 different mods in your pack that are MCreator mods and while I don't know the quality of the system since it has gone fully open source, the history there has me concerned that they might be causing some issues that are just triggered when BaseMetals or MMD OreSpawn run.
> 
>     3. This issue might be because it looks like 60+ mods are doing world-generation of some sort (there are sections of around 130 lines in the log-file you posted that "Profile" World Generation - with it being 2 lines per mod/call, that makes 65 mods).  I do not know for certain, however, and this is why I'm going to be spending a lot of time talking to the rest of the team to see if we can narrow things down or figure out exactly where the issue is coming from.

Disabling Unidict doesn't help.

**Comment by dshadowwolf** [comment]
sorry, but it's 1545 hours here and I'm putting in the work that actually pays for my "fun hobbies", like Modding... Please be patient.

**Comment by Kasia1403** [comment]
Hello, may I know what time is it in Your country ? I would like to know which version of Java should I use for my modpack and which version of Forge.

**Comment by KiriCattus** [comment]
This is not the right place for that kind of support, you'd be better off asking for help with that in either our community Discord server or another community like it https://discord.mcmoddev.com

**Comment by Kasia1403** [comment]
> This is not the right place for that kind of support, you'd be better off asking for help with that in either our community Discord server or another community like it https://discord.mcmoddev.com

I deleted my last question, I don't wanna be banned.

**Comment by Kasia1403** [comment]
> sorry, but it's 1545 hours here and I'm putting in the work that actually pays for my "fun hobbies", like Modding... Please be patient.

What's going on now ? Do You have some free time ? If You're not busy, please answer. And sorry if I woke You up, but I don't know what time is it in Your contry. Now when I'm writing is about 9.50 AM Polish Time.

**Comment by KiriCattus** [comment]
When he’s free wolf will reply, until then accept the rules in the discord server you joined yesterday and ask there, there is plenty of other people to help while Wolf cannot, and we can still see deleted messages so deleting them is pointless but ask in MMD and someone will try to help

**Comment by Kasia1403** [comment]
@KiriCattus OK, I think.

**Comment by Kasia1403** [comment]
I don't know if it's important, but turning fallback_orespawn and using_orespawn in BaseMetals.cfg to false didn't solve this issue.

**Comment by Kasia1403** [comment]
What ?! I noticed that when a mob ( for example pig ) receives damage, player also receives damage ).

**Comment by jriwanek** [comment]
It's quite clear at this point that you're doing one of two things, either you're trolling/timewasting, or you're trying to use our team to debug things in your pack which are *entirely* unrelated to our mods, either way, it's not welcome, issue closed, further abuse of our time will be met with a complete ban from our issue tracker.
