### ISSUE TITLE
Some ores considerably harder than Iron

### ISSUE THREAD

**Issue by jriwanek** [MinecraftModDevelopmentMods/BaseMetals#58]
See: https://github.com/cyanobacterium/BaseMetals/issues/65

**Comment by dshadowwolf** [comment]
Will research fix.

**Comment by dshadowwolf** [comment]
I think this has actually been fixed, but needs more work because now we have a max hardness of 5 instead of a minimum - unless the material is "soft" (which, apparently, also means "can be dug with a shovel")... I think we might want to extend this to a "hard", letting us have ores harder than 5.0f - which could apply to, eg. Adamantium

**Comment by dshadowwolf** [comment]
Closing as (hopefully) resolved.
